/** Versions we know how to speak. The client's choice wins when we know it. */
export const PROTOCOL_VERSIONS = ['2025-06-18', '2025-03-26', '2024-11-05']

export const SERVER_INFO = { name: 'conductor-remote', version: '1' }

export const INSTRUCTIONS =
	'Drives local Conductor agents through the conductor-remote relay. search_chats and read_chat reach archived workspaces, which is where most finished work lives. list_voice_calls, search_voice_calls and read_voice_call read saved fleet-call transcripts without driving the UI. Use delegate_task for lightweight codebase agents in tracked sibling subtabs: list_roles shows the configured roles and their current models, then an ordinary chat supplies session_id, role, and a focused prompt. Choose a configured role whose instructions fit the task, usually exploration for independent code searches, investigation, and verification, including helper work requested by skills such as gstack. Use the configured role settings even when a skill names a model. Each task returns its result to its parent; several independent explorers can run concurrently without starting a planning/exploration/implementation Workflow. Continue useful local work while they run; use return_mode=steer if their result is needed during the current turn, since the default queue delivers behind it. Inside an active Workflow, only its root may delegate, using the workflow_id and current phase_capability from its private envelope. Never bypass that path through ordinary delegation or untracked splits. MCP cannot start a Workflow, edit its frozen roles, or perform recovery actions. delegate_task returns immediately; the relay later drives the real Mac UI to open, configure, and send the child. create_workspace opens its workspace link without direct UI control; requested agent settings and the first prompt are applied later through Conductor’s UI. plan_usage, dev_server status, dismiss_prompt, keep_awake and relay_logs touch no UI. Use dev_server instead of launching a long-lived development server from a shell: its start/stop actions use Conductor’s configured Run task, drive the real Mac UI and steal focus for a few seconds. send_prompt, split_chat, stop_turn, close_chat, set_agent_options, set_default_model, a live list_models call, set_workspace_status and archive_workspace also drive the real Mac UI and steal focus for a few seconds — confirm with the user before using them on a chat or workspace they did not name. archive_workspace also deletes the worktree and stops whatever is running there.'

/** Reads are quick; a UI write is measured in tens of seconds (src/writes/runner.ts ▸ SEND_ATTEMPT_MS). */
export const READ_TIMEOUT_MS = 10_000

export const WRITE_TIMEOUT_MS = 75_000
