import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { exportSql } from 'drizzle-kit/cli'

const root = resolve(import.meta.dirname, '..')
const schemaPath = resolve(root, 'src/orchestration/persistence/schema.ts')
const outputPath = resolve(root, 'src/orchestration/persistence/schema.generated.ts')

const result = await exportSql({ dialect: 'sqlite', schema: schemaPath })
if (result.status === 'error') {
	throw new Error(`Drizzle schema export failed: ${result.error.code}`)
}
if (result.warnings.length > 0) {
	throw new Error(`Drizzle schema export warned:\n${result.warnings.join('\n')}`)
}

const statements = result.statements.map(statement => {
	if (!/^CREATE TABLE\b/i.test(statement)) return statement.trim()
	const strict = statement.trim().replace(/\);$/, ') STRICT;')
	if (!/\) STRICT;$/.test(strict)) throw new Error(`Could not make generated table STRICT:\n${statement}`)
	return strict
})
statements.push('INSERT INTO `ui_mutex` (`id`) VALUES (1);')
statements.push('INSERT INTO `ui_quarantine` (`id`) VALUES (1);')

const sql = `${statements.join('\n\n')}\n`
const escapedSql = sql.replaceAll('`', '\\`').replaceAll('${', '\\${')
const generated = `// Generated by scripts/generate-orchestration-schema.ts. Do not edit.\n\nexport const ORCHESTRATION_BOOTSTRAP_SQL = \`\n${escapedSql}\`\n`

if (process.argv.includes('--check')) {
	let current: string
	try {
		current = readFileSync(outputPath, 'utf8')
	} catch {
		throw new Error('orchestration schema artifact is missing; run yarn db:schema')
	}
	if (current !== generated) throw new Error('orchestration schema artifact is stale; run yarn db:schema')
} else {
	writeFileSync(outputPath, generated)
}
