// Generated by scripts/generate-orchestration-schema.ts. Do not edit.

export const ORCHESTRATION_BOOTSTRAP_SQL = `
CREATE TABLE \`orchestration_meta\` (
	\`key\` text PRIMARY KEY,
	\`value\` text NOT NULL
) STRICT;

CREATE TABLE \`relay_instances\` (
	\`instance_id\` text PRIMARY KEY,
	\`pid\` integer NOT NULL,
	\`process_started_at\` text NOT NULL,
	\`protocol_version\` integer NOT NULL,
	\`can_drive_ui\` integer DEFAULT true NOT NULL,
	\`heartbeat_at\` integer NOT NULL,
	\`registered_at\` integer NOT NULL,
	\`metadata_json\` text,
	CONSTRAINT "relay_instances_can_drive_ui_boolean" CHECK("can_drive_ui" IN (0, 1)),
	CONSTRAINT "relay_instances_metadata_json_valid" CHECK("metadata_json" IS NULL OR json_valid("metadata_json"))
) STRICT;

CREATE TABLE \`ui_mutex\` (
	\`id\` integer PRIMARY KEY,
	\`owner_instance_id\` text,
	\`owner_pid\` integer,
	\`owner_process_started_at\` text,
	\`owner_protocol_version\` integer,
	\`nonce\` text,
	\`action_id\` text,
	\`effect_id\` text,
	\`external_pid\` integer,
	\`external_process_started_at\` text,
	\`external_process_group\` integer,
	\`may_execute\` integer DEFAULT false NOT NULL,
	\`deadline_at\` integer,
	\`acquired_at\` integer,
	\`updated_at\` integer,
	CONSTRAINT "ui_mutex_singleton" CHECK("id" = 1),
	CONSTRAINT "ui_mutex_may_execute_boolean" CHECK("may_execute" IN (0, 1))
) STRICT;

CREATE TABLE \`ui_quarantine\` (
	\`id\` integer PRIMARY KEY,
	\`active\` integer DEFAULT false NOT NULL,
	\`action_id\` text,
	\`effect_id\` text,
	\`reason\` text,
	\`owner_instance_id\` text,
	\`owner_pid\` integer,
	\`owner_process_started_at\` text,
	\`owner_protocol_version\` integer,
	\`external_pid\` integer,
	\`external_process_started_at\` text,
	\`external_process_group\` integer,
	\`created_at\` integer,
	\`cleared_at\` integer,
	\`cleared_by\` text,
	CONSTRAINT "ui_quarantine_singleton" CHECK("id" = 1),
	CONSTRAINT "ui_quarantine_active_boolean" CHECK("active" IN (0, 1))
) STRICT;

CREATE TABLE \`workflow_capabilities\` (
	\`id\` text PRIMARY KEY,
	\`token_hash\` text NOT NULL UNIQUE,
	\`run_id\` text NOT NULL,
	\`root_session_id\` text NOT NULL,
	\`cycle\` integer NOT NULL,
	\`phase\` text NOT NULL,
	\`revision\` integer NOT NULL,
	\`allowed_roles_json\` text NOT NULL,
	\`issued_with_rowid\` integer,
	\`issued_with_turn_id\` text,
	\`consumed_at\` integer,
	\`revoked_at\` integer,
	\`created_at\` integer NOT NULL,
	CONSTRAINT \`fk_workflow_capabilities_run_id_workflow_runs_id_fk\` FOREIGN KEY (\`run_id\`) REFERENCES \`workflow_runs\`(\`id\`) ON DELETE CASCADE,
	CONSTRAINT "workflow_capabilities_token_hash_length" CHECK(length("token_hash") = 64),
	CONSTRAINT "workflow_capabilities_cycle_nonnegative" CHECK("cycle" >= 0),
	CONSTRAINT "workflow_capabilities_revision_nonnegative" CHECK("revision" >= 0),
	CONSTRAINT "workflow_capabilities_allowed_roles_json_valid" CHECK(json_valid("allowed_roles_json"))
) STRICT;

CREATE TABLE \`workflow_effect_attempts\` (
	\`id\` text PRIMARY KEY,
	\`effect_id\` text NOT NULL,
	\`attempt_number\` integer NOT NULL,
	\`state\` text NOT NULL,
	\`owner_instance_id\` text NOT NULL,
	\`owner_pid\` integer NOT NULL,
	\`owner_process_started_at\` text NOT NULL,
	\`owner_protocol_version\` integer NOT NULL,
	\`launch_nonce\` text,
	\`external_pid\` integer,
	\`external_process_started_at\` text,
	\`external_process_group\` integer,
	\`may_execute\` integer DEFAULT false NOT NULL,
	\`receipt_json\` text,
	\`evidence_json\` text,
	\`error_code\` text,
	\`error_message\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	\`terminal_at\` integer,
	CONSTRAINT \`fk_workflow_effect_attempts_effect_id_workflow_effects_id_fk\` FOREIGN KEY (\`effect_id\`) REFERENCES \`workflow_effects\`(\`id\`) ON DELETE CASCADE,
	CONSTRAINT \`workflow_effect_attempts_effect_number_unique\` UNIQUE(\`effect_id\`,\`attempt_number\`),
	CONSTRAINT "workflow_effect_attempts_attempt_positive" CHECK("attempt_number" > 0),
	CONSTRAINT "workflow_effect_attempts_state_valid" CHECK("state" IN ('prepared', 'dispatched', 'committed', 'failed', 'ambiguous', 'cancelled')),
	CONSTRAINT "workflow_effect_attempts_may_execute_boolean" CHECK("may_execute" IN (0, 1)),
	CONSTRAINT "workflow_effect_attempts_receipt_json_valid" CHECK("receipt_json" IS NULL OR json_valid("receipt_json")),
	CONSTRAINT "workflow_effect_attempts_evidence_json_valid" CHECK("evidence_json" IS NULL OR json_valid("evidence_json"))
) STRICT;

CREATE TABLE \`workflow_effects\` (
	\`id\` text PRIMARY KEY,
	\`run_id\` text NOT NULL,
	\`action_id\` text NOT NULL,
	\`job_id\` text,
	\`kind\` text NOT NULL,
	\`state\` text NOT NULL,
	\`target_json\` text,
	\`inputs_json\` text,
	\`baseline_json\` text,
	\`cursor_json\` text,
	\`receipt_json\` text,
	\`error_code\` text,
	\`error_message\` text,
	\`owner_instance_id\` text,
	\`owner_pid\` integer,
	\`owner_process_started_at\` text,
	\`owner_protocol_version\` integer,
	\`launch_nonce\` text,
	\`external_pid\` integer,
	\`external_process_started_at\` text,
	\`external_process_group\` integer,
	\`may_execute\` integer DEFAULT false NOT NULL,
	\`attempt_count\` integer DEFAULT 0 NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	\`terminal_at\` integer,
	CONSTRAINT \`fk_workflow_effects_run_id_workflow_runs_id_fk\` FOREIGN KEY (\`run_id\`) REFERENCES \`workflow_runs\`(\`id\`) ON DELETE CASCADE,
	CONSTRAINT \`fk_workflow_effects_job_id_workflow_jobs_id_fk\` FOREIGN KEY (\`job_id\`) REFERENCES \`workflow_jobs\`(\`id\`) ON DELETE CASCADE,
	CONSTRAINT \`workflow_effects_run_action_unique\` UNIQUE(\`run_id\`,\`action_id\`),
	CONSTRAINT "workflow_effects_state_valid" CHECK("state" IN ('prepared', 'dispatched', 'committed', 'failed', 'ambiguous', 'cancelled')),
	CONSTRAINT "workflow_effects_target_json_valid" CHECK("target_json" IS NULL OR json_valid("target_json")),
	CONSTRAINT "workflow_effects_inputs_json_valid" CHECK("inputs_json" IS NULL OR json_valid("inputs_json")),
	CONSTRAINT "workflow_effects_baseline_json_valid" CHECK("baseline_json" IS NULL OR json_valid("baseline_json")),
	CONSTRAINT "workflow_effects_cursor_json_valid" CHECK("cursor_json" IS NULL OR json_valid("cursor_json")),
	CONSTRAINT "workflow_effects_receipt_json_valid" CHECK("receipt_json" IS NULL OR json_valid("receipt_json")),
	CONSTRAINT "workflow_effects_may_execute_boolean" CHECK("may_execute" IN (0, 1)),
	CONSTRAINT "workflow_effects_attempt_count_nonnegative" CHECK("attempt_count" >= 0)
) STRICT;

CREATE TABLE \`workflow_events\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT,
	\`run_id\` text NOT NULL,
	\`event_key\` text NOT NULL,
	\`type\` text NOT NULL,
	\`data_json\` text,
	\`created_at\` integer NOT NULL,
	CONSTRAINT \`fk_workflow_events_run_id_workflow_runs_id_fk\` FOREIGN KEY (\`run_id\`) REFERENCES \`workflow_runs\`(\`id\`) ON DELETE CASCADE,
	CONSTRAINT \`workflow_events_run_event_key_unique\` UNIQUE(\`run_id\`,\`event_key\`),
	CONSTRAINT "workflow_events_data_json_valid" CHECK("data_json" IS NULL OR json_valid("data_json"))
) STRICT;

CREATE TABLE \`workflow_idempotency\` (
	\`operation\` text NOT NULL,
	\`client_id\` text NOT NULL,
	\`request_hash\` text NOT NULL,
	\`result_json\` text NOT NULL,
	\`run_id\` text,
	\`action_id\` text,
	\`created_at\` integer NOT NULL,
	CONSTRAINT \`workflow_idempotency_pk\` PRIMARY KEY(\`operation\`, \`client_id\`),
	CONSTRAINT \`fk_workflow_idempotency_run_id_workflow_runs_id_fk\` FOREIGN KEY (\`run_id\`) REFERENCES \`workflow_runs\`(\`id\`) ON DELETE SET NULL,
	CONSTRAINT "workflow_idempotency_request_hash_length" CHECK(length("request_hash") = 64),
	CONSTRAINT "workflow_idempotency_result_json_valid" CHECK(json_valid("result_json"))
) STRICT;

CREATE TABLE \`workflow_job_attempts\` (
	\`id\` text PRIMARY KEY,
	\`job_id\` text NOT NULL,
	\`attempt_number\` integer NOT NULL,
	\`state\` text NOT NULL,
	\`child_session_id\` text,
	\`open_effect_id\` text,
	\`configure_effect_id\` text,
	\`task_effect_id\` text,
	\`baton_effect_id\` text,
	\`outcome_json\` text,
	\`failure_evidence_json\` text,
	\`owner_instance_id\` text,
	\`owner_pid\` integer,
	\`owner_process_started_at\` text,
	\`owner_protocol_version\` integer,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	\`terminal_at\` integer,
	CONSTRAINT \`fk_workflow_job_attempts_job_id_workflow_jobs_id_fk\` FOREIGN KEY (\`job_id\`) REFERENCES \`workflow_jobs\`(\`id\`) ON DELETE CASCADE,
	CONSTRAINT \`workflow_job_attempts_job_number_unique\` UNIQUE(\`job_id\`,\`attempt_number\`),
	CONSTRAINT "workflow_job_attempts_attempt_positive" CHECK("attempt_number" > 0),
	CONSTRAINT "workflow_job_attempts_state_valid" CHECK("state" IN ('dormant', 'queued', 'owned', 'opening', 'configuring', 'sending', 'running', 'returning', 'returned', 'failed', 'cancelled')),
	CONSTRAINT "workflow_job_attempts_outcome_json_valid" CHECK("outcome_json" IS NULL OR json_valid("outcome_json")),
	CONSTRAINT "workflow_job_attempts_failure_evidence_json_valid" CHECK("failure_evidence_json" IS NULL OR json_valid("failure_evidence_json"))
) STRICT;

CREATE TABLE \`workflow_jobs\` (
	\`id\` text PRIMARY KEY,
	\`run_id\` text NOT NULL,
	\`logical_key\` text NOT NULL,
	\`role\` text NOT NULL,
	\`cycle\` integer NOT NULL,
	\`revision\` integer NOT NULL,
	\`resolved_role_json\` text NOT NULL,
	\`prompt\` text NOT NULL,
	\`state\` text NOT NULL,
	\`cancellation_generation\` integer NOT NULL,
	\`owner_instance_id\` text,
	\`owner_pid\` integer,
	\`owner_process_started_at\` text,
	\`owner_protocol_version\` integer,
	\`transcript_cursor_json\` text,
	\`child_session_id\` text,
	\`outcome_json\` text,
	\`task_receipt_json\` text,
	\`baton_receipt_json\` text,
	\`attempt_count\` integer DEFAULT 0 NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	\`terminal_at\` integer,
	CONSTRAINT \`fk_workflow_jobs_run_id_workflow_runs_id_fk\` FOREIGN KEY (\`run_id\`) REFERENCES \`workflow_runs\`(\`id\`) ON DELETE CASCADE,
	CONSTRAINT \`workflow_jobs_run_logical_key_unique\` UNIQUE(\`run_id\`,\`logical_key\`),
	CONSTRAINT "workflow_jobs_role_valid" CHECK("role" IN ('exploration', 'implementation')),
	CONSTRAINT "workflow_jobs_cycle_nonnegative" CHECK("cycle" >= 0),
	CONSTRAINT "workflow_jobs_revision_nonnegative" CHECK("revision" >= 0),
	CONSTRAINT "workflow_jobs_resolved_role_json_valid" CHECK(json_valid("resolved_role_json")),
	CONSTRAINT "workflow_jobs_state_valid" CHECK("state" IN ('dormant', 'queued', 'owned', 'opening', 'configuring', 'sending', 'running', 'returning', 'returned', 'failed', 'cancelled')),
	CONSTRAINT "workflow_jobs_cancellation_generation_nonnegative" CHECK("cancellation_generation" >= 0),
	CONSTRAINT "workflow_jobs_transcript_cursor_json_valid" CHECK("transcript_cursor_json" IS NULL OR json_valid("transcript_cursor_json")),
	CONSTRAINT "workflow_jobs_outcome_json_valid" CHECK("outcome_json" IS NULL OR json_valid("outcome_json")),
	CONSTRAINT "workflow_jobs_task_receipt_json_valid" CHECK("task_receipt_json" IS NULL OR json_valid("task_receipt_json")),
	CONSTRAINT "workflow_jobs_baton_receipt_json_valid" CHECK("baton_receipt_json" IS NULL OR json_valid("baton_receipt_json")),
	CONSTRAINT "workflow_jobs_attempt_count_nonnegative" CHECK("attempt_count" >= 0)
) STRICT;

CREATE TABLE \`workflow_runs\` (
	\`id\` text PRIMARY KEY,
	\`objective\` text NOT NULL,
	\`target_json\` text NOT NULL,
	\`roles_json\` text NOT NULL,
	\`phase\` text NOT NULL,
	\`cycle\` integer DEFAULT 0 NOT NULL,
	\`revision\` integer DEFAULT 0 NOT NULL,
	\`workspace_id\` text,
	\`root_session_id\` text,
	\`pristine_evidence_json\` text,
	\`delivery_baseline_json\` text,
	\`planning_interpretation\` text,
	\`cancellation_generation\` integer DEFAULT 0 NOT NULL,
	\`blocked_action_id\` text,
	\`blocked_error_code\` text,
	\`blocked_message\` text,
	\`resume_phase\` text,
	\`retry_class\` text,
	\`blocked_candidates_json\` text,
	\`blocked_at\` integer,
	\`implementation_batons_delivered\` integer DEFAULT 0 NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	\`terminal_at\` integer,
	CONSTRAINT "workflow_runs_target_json_valid" CHECK(json_valid("target_json")),
	CONSTRAINT "workflow_runs_roles_json_valid" CHECK(json_valid("roles_json")),
	CONSTRAINT "workflow_runs_phase_valid" CHECK("phase" IN ('creating_workspace', 'binding_root', 'pending_root', 'exploring', 'planning', 'implementing', 'reviewing', 'blocked', 'completed', 'cancelled')),
	CONSTRAINT "workflow_runs_cycle_nonnegative" CHECK("cycle" >= 0),
	CONSTRAINT "workflow_runs_revision_nonnegative" CHECK("revision" >= 0),
	CONSTRAINT "workflow_runs_pristine_evidence_json_valid" CHECK("pristine_evidence_json" IS NULL OR json_valid("pristine_evidence_json")),
	CONSTRAINT "workflow_runs_delivery_baseline_json_valid" CHECK("delivery_baseline_json" IS NULL OR json_valid("delivery_baseline_json")),
	CONSTRAINT "workflow_runs_cancellation_generation_nonnegative" CHECK("cancellation_generation" >= 0),
	CONSTRAINT "workflow_runs_resume_phase_valid" CHECK("resume_phase" IS NULL OR "resume_phase" IN ('creating_workspace', 'binding_root', 'pending_root', 'exploring', 'planning', 'implementing', 'reviewing')),
	CONSTRAINT "workflow_runs_retry_class_valid" CHECK("retry_class" IS NULL OR "retry_class" IN ('deterministic', 'ambiguous', 'terminal')),
	CONSTRAINT "workflow_runs_blocked_candidates_json_valid" CHECK("blocked_candidates_json" IS NULL OR json_valid("blocked_candidates_json")),
	CONSTRAINT "workflow_runs_implementation_batons_nonnegative" CHECK("implementation_batons_delivered" >= 0)
) STRICT;

CREATE INDEX \`relay_instances_protocol\` ON \`relay_instances\` (\`can_drive_ui\`,\`protocol_version\`,\`heartbeat_at\`);

CREATE INDEX \`workflow_capabilities_current\` ON \`workflow_capabilities\` (\`run_id\`,\`phase\`,\`cycle\`,\`revision\`) WHERE "workflow_capabilities"."consumed_at" IS NULL AND "workflow_capabilities"."revoked_at" IS NULL;

CREATE INDEX \`workflow_effects_runnable\` ON \`workflow_effects\` (\`state\`,\`updated_at\`) WHERE "workflow_effects"."state" = 'prepared';

CREATE INDEX \`workflow_effects_run_state\` ON \`workflow_effects\` (\`run_id\`,\`state\`);

CREATE INDEX \`workflow_events_run\` ON \`workflow_events\` (\`run_id\`,\`id\`);

CREATE INDEX \`workflow_jobs_runnable\` ON \`workflow_jobs\` (\`state\`,\`created_at\`) WHERE "workflow_jobs"."state" = 'queued';

CREATE INDEX \`workflow_jobs_run_state\` ON \`workflow_jobs\` (\`run_id\`,\`role\`,\`state\`);

CREATE UNIQUE INDEX \`workflow_runs_one_active_root\` ON \`workflow_runs\` (\`root_session_id\`) WHERE "workflow_runs"."root_session_id" IS NOT NULL AND "workflow_runs"."phase" NOT IN ('completed', 'cancelled');

CREATE INDEX \`workflow_runs_active_updated\` ON \`workflow_runs\` (\`phase\`,\`updated_at\`) WHERE "workflow_runs"."phase" NOT IN ('completed', 'cancelled');

CREATE INDEX \`workflow_runs_workspace_active\` ON \`workflow_runs\` (\`workspace_id\`,\`phase\`) WHERE "workflow_runs"."phase" NOT IN ('completed', 'cancelled');

INSERT INTO \`ui_mutex\` (\`id\`) VALUES (1);

INSERT INTO \`ui_quarantine\` (\`id\`) VALUES (1);
`
